version: '3.7'

services:
  frontend:
    image: node:${NODE_JS_VERSION_TAG}
    working_dir: "/var/www/docker"
    volumes:
      - "${LOCAL_CODE_PATH}:/var/www/docker"
    ports:
      - "3100:3100" # vite hot reload
    command: >
      bash -c "npm install
      && npm run dev"
    networks:
      klotski-web:
        ipv4_address: "${NODE_JS_IP_ADDRESS}"

  game-rest-api:
    image: gradle:${GRADLE_VERSION_TAG}
    working_dir: /home/gradle/project
    restart: "always"
    ports:
      - '8080:8000'
    depends_on:
      - database
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - ${PROJECT_PATH}:/home/gradle/project
    command: "gradle game-rest-api:bootRun"
    networks:
      klotski-web:
        ipv4_address: "${GAME_REST_API_IP_ADDRESS}"

  database:
    image: postgres:${POSTGRES_TAG}
    restart: "no"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      klotski-web:
        ipv4_address: "${DATABASE_IP_ADDRESS}"

volumes:
  db-volume:
  gradle-cache:

networks:
  klotski-web:
    name: klotski-web
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/24